env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - react
rules:
  react/jsx-props-no-spreading: off

settings:
  import/resolver:
    alias:
      extensions: [ '.js', '.jsx' ]
      map: [ [ "@", "./resources/js" ] ]
